src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\PasswordHasher\Hasher\PasswordHasherAwareInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface/*, PasswordHasherAwareInterface*/
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = ["ROLE_USER"];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type:'boolean')]
    private $gender = null;

    #[ORM\Column(length: 50)]
    private ?string $firstname = null;

    #[ORM\Column(length: 50)]
    private ?string $Lastname = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getGender() : ?bool
    {
        return $this->gender;
    }

    public function setGender(bool $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->Lastname;
    }

    public function setLastname(string $Lastname): static
    {
        $this->Lastname = $Lastname;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    #[ORM\Column(type: Types::INTEGER)]
    private ?string $numtel = null;
    
    public function getNumtel(): ?int
    {
        return $this->numtel;
    }

    public function setNumtel(int $numtel): static
    {
        $this->numtel = $numtel;

        return $this;
    }

    #[ORM\ManyToMany(targetEntity: Groupe::class, inversedBy: 'users')]
    private Collection $groupes;

    #[ORM\OneToMany(targetEntity: Groupe::class, mappedBy: 'chef')]
    private Collection $groupesChef;

    public function __construct()
    {
        $this->groupes = new ArrayCollection();
        $this->groupesChef = new ArrayCollection();
    }

    /**
     * @return Collection<int, Groupe>
     */
    public function getGroupes(): Collection
    {
        return $this->groupes;
    }

    public function addGroupe(Groupe $groupe): static
    {
        if (!$this->groupes->contains($groupe)) {
            $this->groupes[] = $groupe;
            //$this->groupes->add($groupe);
            $groupe->addUser($this);
        }

        return $this;
    }

    public function removeGroupe(Groupe $groupe): static
    {
        $this->groupes->removeElement($groupe);

        return $this;
    }

    /**
     * @return Collection<int, Groupe>
     */
    public function getGroupesChef(): Collection
    {
        return $this->groupesChef;
    }

    public function addGroupesChef(Groupe $groupesChef): static
    {
        if (!$this->groupesChef->contains($groupesChef)) {
            $this->groupesChef->add($groupesChef);
            $groupesChef->setChef($this);
        }

        return $this;
    }

    public function removeGroupesChef(Groupe $groupesChef): static
    {
        if ($this->groupesChef->removeElement($groupesChef)) {
            // set the owning side to null (unless already changed)
            if ($groupesChef->getChef() === $this) {
                $groupesChef->setChef(null);
            }
        }

        return $this;
    }


}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstname')
            ->add('Lastname')
            ->add('numtel')
            ->add('gender')
            ->add('email')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Form\RegistrationFormType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\UserAuthenticatorInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Mime\Address;
use App\Security\AppCustomAuthentificatorAuthenticator;
use App\Security\EmailVerifier;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    private EmailVerifier $emailVerifier;

    public function __construct(EmailVerifier $emailVerifier)
    {
        $this->emailVerifier = $emailVerifier;
    }

    #[Route('/show/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {

        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserPasswordHasherInterface $userPasswordHasher, UserAuthenticatorInterface $userAuthenticator, AppCustomAuthentificatorAuthenticator $authenticator, EntityManagerInterface $entityManager): Response
    {
        $user = new User();
        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );

            $entityManager->persist($user);
            $entityManager->flush();

            // generate a signed url and email it to the user
            $this->emailVerifier->sendEmailConfirmation('app_verify_email', $user,
                (new TemplatedEmail())
                    ->from(new Address('verifyemail@folklore.fr', 'Zeus'))
                    ->to($user->getEmail())
                    ->subject('Please Confirm your Email')
                    ->htmlTemplate('registration/confirmation_email.html.twig')
            );
            // do anything else you need here, like send an email

            return $userAuthenticator->authenticateUser(
                $user,
                $authenticator,
                $request
            );
        }

        return $this->render('registration/register.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }

    
    /**
     * @Route("/mon-compte", name="app_user_account", methods={"GET"})
     */
    #[Route('/mon-compte', name: 'app_user_account', methods: ['GET'])]
    public function account(): Response
    {
        $user = $this->getUser();
        
        return $this->render('user/account.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_home');
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete.html.twig
<form method="post" action="{{ path('app_delete', {'id': user.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet utilisateur ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-danger btn-sm">Supprimer</button>
</form>

templates/user/_form.html.twig
<form method="post" action="{{ path('app_user_edit', {'id': user.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir modifier cet utilisateur ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('save' ~ user.id) }}">
    <button class="btn btn-success btn-sm">Enregistrer</button>
</form>

templates/user/account.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

<div class="container mt-5">

<table class="table table-bordered table-striped">
        <h2>Mon compte</h2>
        <thead class="thead-dark">
            <tr>
                <th>Prénom :</th>
                <td>{{ user.firstname }}</td>
            </tr>
            <tr>
                <th>Nom :</th>
                <td>{{ user.lastname }}</td>
            </tr>
            <tr>
                <th>Civilité :</th>
                <td>{{ user.gender ? 'Femme' : 'Homme' }}</td>
            </tr>
            <tr>
                <th>Email :</th>
                <td>{{ user.email }}</td>
            </tr>
        </thead>
    </table>
        <div class="d-flex justify-content-start mt-3">
            <a href="{{ path('app_user_edit', {'id': user.id}) }}" class="btn btn-primary btn-sm me-2">Modifier</a>
            {{ include('user/_delete.html.twig') }}
        </div>
        <div class="d-flex justify-content-end">
            <a class="btn btn-danger btn-sm" href="{{ path('app_logout') }}">Déconnexion</a>
        </div>
</div>
{% endblock %}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

<div class="container mt-5">
{{ form_start(form) }}
{{ form_widget(form) }}

<button type="submit" class="btn btn-primary">Modifier</button>

{% if is_granted('IS_AUTHENTICATED_FULLY') %}
<a href="{{ path('app_user_index') }}">back to list</a>
{% endif %}

{{ form_end(form) }}

</div>

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

<div class="container mt-5">

<table class="table table-bordered table-striped">
        <h2>Tableau des Utilisateurs</h2>
        <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>Prenom</th>
                <th>Nom</th>
                <th>Numéro de téléphone</th>
                <th>Civilité</th>
                <th>Roles</th>
                <th>Email</th>
                <th>Password</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.firstname }}</td>
                <td>{{ user.lastname }}</td>
                <td>{{ user.numtel }}</td>
                <td>{{ user.gender ? 'Femme' : 'Homme' }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.password }}</td>
                <td>
                
                    <a href="{{ path('app_user_show', { 'id': user.id }) }}">Détails</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_user_new') }}">Create new</a>
</div>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <form method="post">

    <div class="position-relative">
        <div class="position-absolute top-0 start-50 translate-middle">
            <h1 class="h3 mb-3 font-weight-normal">Créer un nouvel utilisateur !</h1>
        </div>
    </div>

    {{ form_errors(registrationForm) }}

    <div class="container mt-5">
        {{ form_start(registrationForm) }}
            <div class="form-group">
                {{ form_row(registrationForm.firstname) }}
            </div>
            <div class="form-group">
                {{ form_row(registrationForm.lastname) }}
            </div>
            <div class="form-group">
                {{ form_row(registrationForm.gender) }}
            </div>
            <div class="form-group">
                {{ form_row(registrationForm.numtel) }}
            </div>
            <div class="form-group">
                {{ form_row(registrationForm.email) }}
            </div>
            <div class="form-group">
                {{ form_row(registrationForm.plainPassword) }}
            </div>
            <div class="form-group">
                {{ form_row(registrationForm.confirmPassword) }}
            </div>
            <div class="form-group">
                {{ form_row(registrationForm.agreeTerms) }}
            </div>
            <div class="form-group mt-3">
                <button class="btn btn-lg btn-primary" type="submit">
                    Connexion
                </button>
            </div>            
        {{ form_end(registrationForm) }}
    </div>

</form>       

    <a href="{{ path('app_user_index') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

<div class="container mt-5">
        <h1>Détais du user</h1>
        <table class="table table-bordered table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>Prénom :</th>
                    <td>{{ user.firstname }}</td>
                </tr>
                <tr>
                    <th>Nom :</th>
                    <td>{{ user.lastname }}</td>
                </tr>
                <tr>
                    <th>Civilité :</th>
                    <td>{{ user.gender ? 'Femme' : 'Homme' }}</td>
                </tr>
                <tr>
                    <th>Email :</th>
                    <td>{{ user.email }}</td>
                </tr>
                <tr>
                    <th>MDP :</th>
                    <td>{{ user.password }}</td>
                </tr>
                <tr>
                    <th>Actions</th>
                    <td>
                        <a href="{{ path('app_user_edit', {'id': user.id}) }}" class="btn btn-primary btn-sm">Modifier</a>

                        {{ include('user/_delete.html.twig') }}
                    </td>
                </tr>
            </thead>
        <a href="{{ path('app_user_index') }}">back to list</a>
        </table>
</div>
{% endblock %}